### ISSUE TITLE
Newest is not the newest but highest of the newest

### ISSUE THREAD

**Issue by JordyMoos** [JordyMoos/JMPriceSuggestion#3]
Should be ordered on newest (best guild)

Same for cheapest. Should be cheapest of all guilds

**Comment by marcusklaas** [comment]
Should this issue not be here: https://github.com/JordyMoos/JMPriceTooltip?

**Comment by JordyMoos** [comment]
Yea it should i will move it

**Comment by JordyMoos** [comment]
https://github.com/JordyMoos/JMPriceTooltip/issues/2
